FROM docker.1ms.run/rlinf/rlinf:agentic-rlinf0.3-maniskill_libero

ENV VIRTUAL_ENV=/opt/venv/libero \
    PATH="/opt/venv/libero/bin:${PATH}" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN uv venv --python 3.10.15 "${VIRTUAL_ENV}"

ENV UV_DEFAULT_INDEX=https://pypi.tuna.tsinghua.edu.cn/simple

RUN uv pip install \
      'ray[default]==2.55.1' \
      torch==2.9.0 \
      torchvision==0.24.0 \
      torchaudio==2.9.0 \
      rlinf-libero \
      omegaconf \
      gymnasium==1.3.0

RUN mkdir -p \
      /opt/venv/libero/lib/python3.10/site-packages/libero/libero/assets \
    && cp -a \
      /opt/envs/LIBERO/libero/libero/assets/. \
      /opt/venv/libero/lib/python3.10/site-packages/libero/libero/assets/

WORKDIR /workspace

CMD ["/bin/bash"]